### ISSUE TITLE
what can be done about this?

### ISSUE THREAD

**Issue by KhaozFrost** [bonn2/BigDoorsPhysics#10]
```
[17:19:32 ERROR] [Minecraft]: Error occurred while enabling BigDoorsPhysics v2.3.5 (Is it up to date?)
java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.Server.getMinecraftVersion()'
        at net.bonn2.bigdoorsphysics.BigDoorsPhysics.onEnable(BigDoorsPhysics.java:41) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:264) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23192!/:arclight-1.19.2-1.0.1-0550c6cd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23192!/:arclight-1.19.2-1.0.1-0550c6cd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23192!/:arclight-1.19.2-1.0.1-0550c6cd]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServerMixin.java:525) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23192!/:arclight-1.19.2-1.0.1-0550c6cd]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServerMixin.java:439) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23192!/:arclight-1.19.2-1.0.1-0550c6cd]
        at net.minecraft.server.MinecraftServer.handler$zfc000$arclight$enablePlugins(MinecraftServerMixin.java:2194) ~[server-1.19.2-20220805.130853-srg.jar%23227!/:?]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:375) ~[server-1.19.2-20220805.130853-srg.jar%23227!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:300) ~[server-1.19.2-20220805.130853-srg.jar%23227!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:165) ~[server-1.19.2-20220805.130853-srg.jar%23227!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2087) ~[server-1.19.2-20220805.130853-srg.jar%23227!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23227!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by bonn2** [comment]
BigDoorsPhysics requires paper, that error happens when running under spigot
